# Generated by Django 4.2.4 on 2023-08-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=500, verbose_name='Описание'),
        ),
    ]
