# Generated by Django 4.2.4 on 2023-08-26 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maps', '0002_alter_location_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField(verbose_name='Время начала')),
                ('endTime', models.DateTimeField(verbose_name='Время конца')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.location', verbose_name='Место')),
            ],
        ),
    ]
